language: node_js
node_js:
  - lts/*
install:
  - npm ci
script:
  - npm run docs:build
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: docs/src/.vuepress/dist
  github_token: ${{ secrets.ACCESS_TOKEN }}
  keep_history: true
  on:
    branch: create-website-for-project